
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://a1bhinav.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""
cv: "AbhinavSharma.pdf"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Abhinav Sharma"
title: "{ Abhinav Sharma }"
description: "By the perplexed, for the perplexed - Abhinav Sharma"
keywords: "abhinav, sharma"
favicon: "/img/geek.png"

################
# Header layout #
################

black-favicon: "/img/geek.png"

background-img: "../img/intro-bg.jpeg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 8
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Life is too short to write documentation."
  - text: "Just kidding, go document your code."
  - text: "Where’s your will to be weird?"

me-img: "/img/author.jpeg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
# google-plus-share: True
# tumblr-share: True
pinterest-share: True
pocket-share: True
# vkontakte-share: True

# disqus-shortname: "yugesh-kothari"

syntax-highlight: True

############
# Timeline #
############

events:
  - image : "/img/timeline/amazon.png"
    date :  "Jan 2023 - Jun 2023"
    description : "Upcoming SDE Intern \n\n Amazon"
  - image : "/img/timeline/tudelft.png"
    date : "June 2022 - Present"
    description : "Research Intern \n\n TU Delft"
  - image: "/img/timeline/aisys.png"
    date : "Jun 2022 - Present"
    description : "Research Specialist \n\n AISys Lab"
  - image: "/img/timeline/sharc.png"
    date : "Jun 2021 - Jan 2022"
    description : "Research Intern \n\n Sharc Lab"
  - image : "/img/timeline/shike.webp"
    date : "Aug 2020 - Mar 2021"
    description : "Project Manager \n\n Shikedum Learning"
  - image: "/img/timeline/Progateg.png"
    date: "June 2020 - Aug 2020"
    description: "Community Developement Intern \n Progate"

# First image of the Timeline

timeline-img: "/img/timeline/iiitg.png" 

###########
# Contact #
###########

email: "abhinav.sharma@iiitg.ac.in"
phone: "Ph: Available on request"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# Works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Abhinav is a senior year student at IIIT G. His research interests include autonomous systems, CV and ML."
author_blurb_image: "/img/author.jpeg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/profile.php?id=100037989287257"
  - title: "twitter"
    url: "https://twitter.com/a1bhinav"
  - title: "github"
    url: "https://github.com/a1bhinav"

############
# 404 page #
############

err-404-img: "/img/geek_old.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Research: 'research'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'
  Resume: 'cv'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
